### ISSUE TITLE
Organize the examples into tutorials

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank-examples#11]
We will want to make our examples into proper numbered tutorials. These should also be documented in the online faq

**Comment by jchodera** [comment]
I don't think they should be numbered.

The standard use case is for someone to want to jump into the docs or examples directory to find an example close to what they are trying to do, then modify it. Also, we will want to add more examples later and a numbering system may not hold up.

So let's definitely find a way to bring the examples in as tutorials or illustrative examples in the docs, but no need to number them. Grouping them by logical category:
- hydration free energies, or maybe even the more general "transfer free energies" since we can support non aqueous phases and relative partition coefficients
  *absolute binding free energies

**Comment by andrrizzi** [comment]
> since we can support non aqueous phases

Just to clarify, we currently don't support in the YAML pipeline any other type of solvation than with TIP3P water, so it is possible to run transfer free energies only starting from existing amber files (although I've never tested it).

**Comment by jchodera** [comment]
Right, but we will add this at some point soon (post-1.0), and it seems better to pick a way to organize for the examples that won't need reworked once we add that support.

**Comment by jchodera** [comment]
I don't think they should be numbered.

The standard use case is for someone to want to jump into the docs or
examples directory to find an example close to what they are trying to do,
then modify it. Also, we will want to add more examples later and a
numbering system may not hold up.

So let's definitely find a way to bring the examples in as tutorials or
illustrative examples in the docs, but no need to number them. Grouping
them by logical category:
- hydration free energies, or maybe even the more general "transfer free
  energies" since we can support non aqueous phases and relative partition
  coefficients
  *absolute binding free energies

**Comment by Lnaden** [comment]
Tutorials are handled by main yank documentation
